version: "3"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    working_dir: "/frontend"
    volumes:
      - "./frontend/:/frontend"
    ports:
      - "4200:4200"

  backend:
    container_name: backend
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env.dev
    ports:
      - "5000:5000"
    working_dir: "/backend"
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=pass"
      - "POSTGRES_DB=db"
      - "POSTGRES_HOST_AUTH_METHO=trust"
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  postgres_data:
